version: '2'
services:
  mysql:
    build: mysql
    env_file:
      - .env
    volumes:
      - /data/moodle-mysql:/var/lib/mysql
    dns:
      - 172.17.0.1
    networks:
      app_net:

  moodle:
    build: moodle
    links:
      - mysql
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/letsencrypt:/etc/letsencrypt
    dns:
      - 172.17.0.1
    networks:
      app_net:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.17.0.0/24